version: '3'

services:
  api:
    build: helpo-api/.
    restart: always
    env_file:
      - helpo-api/.env
    expose:
      - "8000"
    volumes:
      - ./logs/django:/code/logs
  web:
    image: helpo/helpo_web
    restart: always
    env_file:
      - helpo-web/.env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./certs:/certs
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api
  pgadmin:
    image: fenglc/pgadmin4:alpine
    restart: always
    env_file:
      - ./pgadmin.env
    expose:
      - "5050"

# Meant to be used alone, made for pulling from aws
# docker-compose -f docker-compose.aws.yml COMMAND