version: '3'

services:
  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-helpo
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build: helpo-api/.
    restart: always
    command: ["./wait-for-it.sh", "db:5432", "--", "bash", "-c", 
      "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    expose:
      - "8000"
    depends_on:
      - db
  web:
    image: helpo/helpo_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./certs:/certs
    depends_on:
      - db
      - api
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./pgadmin.env
    expose:
      - "443"
    volumes:
      - ./certs/public.pem:/certs/server.crt
      - ./certs/private.pem:/certs/server.key
    depends_on:
      - db

# Meant to be used alone, made for pulling from aws
# docker-compose -f docker-compose.aws.yml COMMAND