import React from 'react';
import { Card, CardHeader, CardBody } from 'reactstrap';

class PageTyC extends React.Component {
  render() {
    return (
      <div className="animated fadeIn">
        <Card>
          <CardHeader>
            <i className="fa fa-align-justify" /> Términos y condiciones
          </CardHeader>
          <CardBody>
                Este convenio describe los términos y condiciones generales (los "Términos y Condiciones Generales") aplicables al uso de los servicios ofrecidos por  el sitio web HELPO (en adelante “el Sitio”).
                Cualquier persona, ya sea física o jurídica, (en adelante "Usuario" o en plural "Usuarios") que desee acceder y/o usar el sitio o los servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales, junto con todas las demás políticas y principios que rigen el Sitio.
                SI CUALQUIER PERSONA NO ACEPTA ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE PERENTORIAMENTE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS. El Usuario debe leer, entender y aceptar todas y cada una de las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad, así como en los demás documentos incorporados a los mismos por referencia, previo a su registración como Usuario del Sitio.
                Este contrato ayudará a que el Sitio se mantenga como un sitio seguro para la interacción entre entidades públicas y/o organizaciones del tercer sector con voluntarios. El Sitio se basa en la confianza y en la honestidad de sus Usuarios, para que se puedan realizar interacciones en un ambiente amistoso y confiable, y por ende los Usuarios aceptan y se comprometen de antemano a contribuir en su ejecución.
                Alcance de los Términos y Condiciones Generales:
                Los presentes Términos y Condiciones Generales, así como también las normas que los complementan sólo serán aplicables a los servicios y contenidos prestados y/o accesibles directamente en el Sitio y no a aquellos a los que los Usuarios puedan acceder a través de un hipervínculo (link), una barra co-branded, y/o cualquier otra herramienta de navegación ubicada en el Sitio que los lleve a navegar un recurso diferente. La probable aparición de dichos links en el Sitio no implica de modo alguno la asunción de garantía por parte de HELPO sobre los productos, servicios o programas contenidos en ninguna página vinculada al Sitio por tales links. Declara HELPO no haber revisado ninguna de las páginas a las que pueda llegar a accederse desde el Sitio y, en consecuencia, deslinda toda responsabilidad por el contenido de las mismas. En atención a ello, la utilización de los links para navegar hacia cualquier otra página queda al exclusivo criterio responsabilidad y riesgo de los Usuarios.
                Capacidad
                Nuestros servicios sólo están disponibles para personas que tengan capacidad legal para contratar, conforme a las leyes del lugar en donde estén domiciliadas. No podrán utilizar los servicios, los menores de edad, quienes no tengan esa capacidad o las personas que hayan sido suspendidas o dadas de baja del sistema de el Sitio, temporal o definitivamente, por haber incumplido los Términos y Condiciones Generales o por haber incurrido a criterio de el Sitio en conductas o actos dolosos o fraudulentos mediante el uso del sitio o de los servicios. Si está registrando un Usuario como representante de una empresa o persona jurídica, debe tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este contrato.
                Registración
                Es obligación de todo futuro usuario completar el formulario de inscripción, en todos sus campos con datos válidos, a los fines de poder utilizar los servicios ofrecidos por el Sitio. El futuro usuario deberá completar dicho formulario con su información personal de manera exacta, precisa, y verdadera (en adelante “Datos Personales”), y asumirá el compromiso de mantener los Datos Personales actualizados, conforme resulte necesario y/o le sea requerido. El Sitio podrá utilizar diferentes medios para identificar a los usuarios, pero no se responsabiliza por la certeza de los Datos Personales provistos por los usuarios en el formulario de inscripción completado. El usuario, en todos y cada uno de los casos, garantiza y responde ante la autenticidad, exactitud, veracidad, y vigencia de los Datos Personales ingresados en el formulario de inscripción. El Sitio se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, así como de inhabilitar a aquellos usuarios que en un período razonable no logre contactar o bien, que al momento de la verificación no quieran confirmar sus datos. En este caso de inhabilitación, se dará de baja toda la información y actividad registrada por el usuario y/o sus intervenciones en la página web, sin que ello genere algún derecho a resarcimiento.
                El Usuario accederá a su Cuenta Personal (en adelante “cuenta”) mediante el ingreso de su correo electrónico y/o cuenta a la red social elegida para dicho acceso, y su Password o Clave de Seguridad ambos elegidos por él al momento de la inscripción. La cuenta que el Usuario utilice dentro de el Sitio no podrá generar confusiones con el nombre de el Sitio. Por lo tanto, no se podrán utilizar cuentas tales como "Sitio1", o "HelpoOrg", o similares, de tal forma que los demás Usuarios puedan pensar que la información, actividades, y/o interacciones consignadas por estas personas pertenecen a el Sitio o hacen parte de promociones llevadas a cabo directamente por el Sitio. El Sitio se reserva el derecho de eliminar del sistema los Cuentas que a criterio de el Sitio puedan tener las características a que hace referencia este párrafo. El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad. El Usuario será responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar a el Sitio en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. La utilización de la Cuenta es personal y exclusiva de su usuario  titular, por lo que se prohíbe su venta, cesión o transferencia bajo ningún título. El Sitio se reserva el derecho de rechazar cualquier solicitud de inscripción o de cancelar una inscripción previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.
                Modificaciones del Acuerdo
                El Sitio podrá modificar en cualquier momento los Términos y Condiciones Generales de este convenio en cualquier momento, y notificará los cambios al Usuario publicando una versión actualizada de dichos Términos y Condiciones Generales en el Sitio. Dentro de los 5 (cinco) días siguientes a la publicación de las modificaciones introducidas, el Usuario deberá comunicar vía e-mail si no acepta las mismas; en ese caso quedará disuelto el vínculo contractual, y se procederá automáticamente a la inhabilitación de su cuenta registrada en el Sitio. Vencido el plazo mencionado, sin que el Usuario haya manifestado su negativa a aceptar los nuevos Términos y Condiciones Generales, se considerará que el Usuario acepta los nuevos términos y el contrato continuará vinculando a ambas partes.
                Privacidad de la información
                Para utilizar los Servicios ofrecidos por este el Sitio, los Usuarios deberán facilitar determinados datos de carácter personal (en adelante “Datos Personales”). Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica. Este Portal asegura la confidencialidad de los datos suministrados por los Usuarios. No obstante, el Sitio revelará a las autoridades públicas competentes los Datos Personales y cualquier otra información que esté en su poder o sea accesible a través de sus sistemas y sea requerida de conformidad con las disposiciones legales y reglamentarias aplicables al caso.
                Los Usuarios tienen reconocidos y podrán ejercitar los derechos de acceso, cancelación, rectificación y oposición poniéndose en comunicación con el Sitio a través del correo electrónico consultas@helpo.com.ar.
                Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales facilitados, y se comprometen a mantenerlos debidamente actualizados.
                El Sitio no venderá, alquilará ni negociará con otras empresas su información personal. Estos datos serán usados únicamente para la búsqueda, selección, interacción, y transacciones similares que puedan ocurrir entre los distintos usuarios que utilicen la página web en cuestión. El Sitio no venderá su base de datos a otras empresas u organizaciones.
                Gratuidad
                El registro, así como toda utilización e interacción en el Sitio es gratuita. Al realizar transacciones con otros usuarios, el Usuario no deberá pagar cargo alguno a través o fuera de el Sitio.
                Derechos y deberes de los usuarios
                Derechos de los usuarios:
                1- A no ser discriminados por razón alguna, respetando su personalidad, dignidad humana e intimidad.
                2- A recibir en todo momento un trato humano, amable, comprensivo y respetuoso.
                3- A recibir, tanto con carácter inicial como permanente, la información, orientación, apoyo necesario para el ejercicio de las funciones que se le asignen.
                4- A tener oportunidades de aprendizaje y progreso.
                Deberes de los usuarios:
                1- Mantener actualizado permanentemente sus datos personales.
                2- Cumplir los compromisos adquiridos con las organizaciones en las que se integren, respetando los fines y la normativa de las mismas.
                3- Guardar, cuando proceda, confidencialidad de la información recibida y conocida en el desarrollo de su actividad.
                4- Respetar los derechos de los demás usuarios de El Sitio.
                5- Actuar de forma diligente y solidaria.
                6- Seguir las instrucciones adecuadas a los fines que se impartan en el desarrollo de las actividades encomendadas.
                Prohibiciones
                No está permitido el uso de ningún dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de el Sitio como en las bases de datos de el Sitio. Las conducta de los Usuarios dentro de el Sitio será controlada permanentemente por el Sitio, que adoptará las medidas o sanciones establecidas en este contrato. Cualquier intromisión, tentativa o actividad violatoria o contraria a la leyes sobre derecho de autor y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.
                Violaciones al sistema o base de datos
                No está permitido el uso de ningún dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de el Sitio como en las bases de datos de el Sitio. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de autor y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.
                Sanciones y suspensión de transacciones
                Sin perjuicio de otras medidas, el Sitio podrá advertir, suspender o cancelar, temporal o definitivamente la Cuenta de un Usuario en cualquier momento, cesar de prestar sus servicios, e iniciar las acciones legales que correspondan, si se quebrantara cualquiera de las estipulaciones de este contrato, si se imcumpliera cualquier tipo de compromiso como Usuario, si se incurre a criterio de el Sitio en conductas o actos dolosos o fraudulentos, o bien si no pudiera verificarse la identidad del Usuario o cualquier información proporcionada por el mismo fuere errónea. En el caso de la suspensión o inhabilitación de un Usuario, toda la información y actividad registrada y publicada, vinculada a dicho Usuario también serán removidas del sistema.
                El Sitio se reserva el derecho de cancelar la Cuenta del Usuario que hubiere incumplido sus obligaciones,  o si se detectara en su conducta intencionalidad de perjudicar a otros Usuarios. El Sitio se reserva el derecho a cancelar una cuenta registrada por razones no mencionadas anteriormente o si considera que el Usuario ha incurrido en algún error involuntario o por cualquier otra razón que el Sitio considere justificada. El Sitio podrá aplazar, interrumpir, o terminar una transacción en cualquier momento en virtud de una violación a las cláusulas previstas en este acuerdo o por cualquier otra razón. El Sitio se reserva el derecho a cancelar una transacción por razones no mencionadas anteriormente o si considera que el Usuario ha incurrido en algún error involuntario o por cualquier otra razón que el Sitio considere justificada.
                Responsabilidad
                El Sitio sólo pone a disposición de los Usuarios un espacio virtual gratuito, sin costo de publicación . Esta página web sólo permite a los Usuarios ponerse en comunicación y/o interactuar entre sí, en forma libre y voluntaria, a través del medio que consideren más adecuado. El Sitio no es el propietario, patrocinador, ni responsable de los datos suministrados por los Usuarios y consignados en la página web. El Sitio no interviene en el perfeccionamiento de las operaciones, transacciones, e interacciones realizadas entre los Usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello no será responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de las mismas, así como de la capacidad para contratar de los Usuarios o de la veracidad de los Datos Personales por ellos ingresados. Cada Usuario conoce y acepta ser el exclusivo responsable por los Datos Personales y demás información que publica, y por las actividades que realiza en la página web. Debido a que el Sitio no tiene ninguna participación durante todo el tiempo en que las partes se dan a conocer y/o interactúan, y en el perfeccionamiento del contrato definitivo entre las partes, no será responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de las interacciones, transacciones y operaciones. El Usuario conoce y acepta que al realizar operaciones con otros Usuarios o terceros lo hace bajo su propio riesgo. En ningún caso el Sitio será responsable por el daño emergente o lucro cesante, o por cualquier otro perjuicio que haya podido sufrir el Usuario, debido a las interacciones, transacciones, y operaciones realizadas o no realizadas por publicaciones anunciadas a través de este Sitio Web. El Sitio recomienda actuar con prudencia y la debida diligencia, al momento de realizar interacciones, transacciones, y operaciones con otros Usuarios. El Usuario debe tener presentes, además, los riesgos de contratar con menores o con personas que se valgan de una identidad falsa. Dado el enorme volumen de la comunidad electrónica, el Sitio no puede constatar la veracidad y exactitud de los datos consignados por los Usuarios al registrarse en la página web. El Sitio no será responsable por las publicaciones, ni por las interacciones, transacciones, y operaciones realizadas con otros Usuarios basadas en la confianza depositada en el sistema o los Servicios brindados por esta página web. En caso que uno o más Usuarios o algún tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a el Sitio y a sus directores, gerentes, empleados, agentes, operarios, representantes y apoderados.
                Alcance del servicio
                Este convenio no crea ningún contrato de sociedad, de mandato, de franquicia, publicidad, o relación laboral entre el Sitio y el Usuario. El Usuario reconoce y acepta que el Sitio no es parte en ninguna operación, ni tiene control alguno sobre la calidad, cantidad, estado, integridad, seguridad, legitimidad o legalidad de los datos, información, y publicaciones anunciadas, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para operar, obrar y/o interactuar, así como la capacidad para contratar de los Usuarios. Los Usuarios reconocen que toda modalidad de contratación y toda operación surgida entre las partes está sujeta a regulaciones específicas con las cuales deberá cumplimentar. El Sitio no segura que un Usuario completará una operación ni podrá verificar la identidad o Datos Personales ingresados por los Usuarios. El Sitio no garantiza la veracidad de la publicidad de terceros que aparezca en el sitio, y no será responsable por la correspondencia o contratos que el Usuario celebre con dichos terceros o con otros Usuarios.
                Fallas en el sistema
                El Sitio no se responsabiliza por cualquier daño, perjuicio o pérdida en el equipo del Usuario causada por fallos en el sistema, en el servidor o en Internet. El Sitio tampoco será responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o examen de su sitio web o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenidos en el mismo. Los Usuarios NO podrán imputarle responsabilidad alguna ni exigir pago por daño emergente o lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas o fallos en los sistemas o en Internet. El Sitio no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades técnicas o fallos de Internet, o por cualquier otra circunstancia ajena a el Sitio; en tales casos se procurará restablecerlo con la mayor rapidez posible sin que por ello pueda imputársele algún tipo de responsabilidad. El Sitio no será responsable por ningún error u omisión contenidos en su sitio web.
                Propiedad intelectual
                Los contenidos de las pantallas relativas a los servicios de el Sitio como así también los programas, bases de datos, redes, archivos que permiten al Usuario acceder y usar su Cuenta, son de propiedad de el Sitio y están protegidas por las leyes y tratados internacionales de derecho de autor, marcas, patentes, modelos y diseños industriales. El uso indebido y la reproducción total o parcial de dichos contenidos, salvo autorización expresa y por escrito de el Sitio, quedan prohibidos, están penados por la ley con sanciones civiles y penales, y serán objeto de todas las acciones judiciales pertinentes.  El Sitio respeta la propiedad intelectual y solicita a sus Usuarios a realizar lo mismo.
                Indemnización
                El Usuario indemnizará y mantendrá indemne a el Sitio, sus filiales, empresas controladas y/o controlantes, directivos, administradores, representantes y empleados, por cualquier reclamo o demanda de otros Usuarios o terceros por sus actividades en el Sitio Web o por su incumplimiento los Términos y Condiciones Generales, que se entienden incorporadas al presente o por la violación de cualesquiera leyes o derechos de terceros, incluyendo los honorarios de abogados en una cantidad razonable.
                Ley aplicable y jurisprudencia
                Este acuerdo estará regido en todos sus puntos por las leyes vigentes en la República Argentina. Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretación, alcance o cumplimiento, será sometida a los Tribunales con Competencia Ordinaria de la Provincia de Córdoba. Las partes renuncian al fuero Federal y/o todo otro de excepción que les pudieren corresponder.
          </CardBody>
        </Card>
      </div>
    );
  }
}

export default PageTyC;