import React from 'react';
import { Card, CardHeader, CardBody } from 'reactstrap';

class PageTyC extends React.Component {
  render() {
    return (
      <div className="animated fadeIn">
        <Card>
          <CardHeader>
            <i className="fa fa-align-justify" /> Términos y condiciones
          </CardHeader>
          <CardBody>
            <p align='justify'>Los presentes Términos y Condiciones Generales (los “Términos y Condiciones Generales”) regulan la utilización del Sitio Web: www.helpo.com.ar (en adelante el “Sitio”) que Helpo (en adelante “Helpo”), pone a disposición de aquellos interesados que se registren en el mismo (en adelante el “Usuario” o en plural, los “Usuarios”), con el objeto de facilitar al Usuario el acceso a una red de contactos para interactuar, generar relaciones de colaboración y voluntariado, y demás funcionalidades que se agreguen a futuro en el Sitio (en adelante los “Servicios”)</p>
            <p align='justify'>Cualquier persona, ya sea física o jurídica que desee acceder y/o usar el Sitio o los Servicios podrá hacerlo sujetándose a los presentes Términos y Condiciones Generales, junto con todas las demás políticas y principios que rigen el Sitio.</p>
            <p align='justify'><strong>SI CUALQUIER PERSONA NO ACEPTA ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS. </strong></p>
            <p align='justify'>En tal sentido, el Usuario declara haber leído, comprendido y aceptado todos y cada uno de los términos y condiciones establecidos en los presentes Términos y Condiciones Generales, así como sus documentos complementarios y aquellos que se incorporen en un futuro, previo a su registración cómo Usuario del Sitio.</p>
            <p align='justify'>Los Términos y Condiciones Generales tienen por objeto contribuir a la seguridad del Sitio como ámbito de interacción entre entidades públicas, privadas, y/o las denominadas “organizaciones sociales y/o del tercer sector” con aquellos voluntarios que se registren como Usuarios.</p>
            <p>El Sitio se basa en la confianza, buena fe, probidad y honestidad de sus Usuarios con el objeto de posibilitar la interacción de todos en un ambiente amistoso, cordial y confiable. En base a ello, los Usuarios aceptan y se comprometen a comportarse bajo dichas premisas y contribuir al objeto del Sitio.</p>
            <h5>1. ALCANCE DE LOS TÉRMINOS Y CONDICIONES GENERALES.</h5>
            <p align='justify'>1.1. Los presentes Términos y Condiciones Generales, así como también las normas que los complementan y/o complementen a futuro, sólo serán aplicables a los Servicios y contenidos prestados y/o accesibles en forma directa y/o inmediata a través del Sitio y no otros a los que los Usuarios puedan acceder a través de un hipervínculo (link), barra co-branded y/o cualquier otra herramienta de navegación ubicada y/o relacionada en el Sitio que los lleve a navegar en un ámbito y/o sitio distinto del contemplado en los presentes Términos y Condiciones.</p>
            <p align='justify'>1.2. La probable aparición de dichos links en el Sitio no implican en modo alguno la asunción de responsabilidad y/o garantía por parte de Helpo sobre los contenidos, productos, servicios y/o cualquier otro bien ofrecido y/o puesto a disposición en dichas páginas. </p>
            <p align='justify'>1.3. En tal sentido, Helpo deslinda cualquier tipo de responsabilidad por el contenido de dichas páginas y, en consecuencia, la utilización de los links que pudiesen aparecer en el Sitio, así como cualquier navegación y/o ingreso a los entornos que los mismos vinculen, se efectuaran a criterio, riesgo y responsabilidad exclusiva de los Usuarios. </p>
            <h5>2. CAPACIDAD.</h5>
            <p align='justify'>2.1. Podrán ser Usuarios del Sitio, personas humanas mayores de edad y/o con capacidad jurídica plena y/o suficiente para vincularse por los presentes Términos y Condiciones, utilizar y, en su caso, contratar los Servicios puestos a disposición en el Sitio.</p>
            <p align='justify'>2.2. Las personas jurídicas podrán ser Usuarios del Sitio en la medida que la persona física que las inscriba y/o registre tenga capacidad jurídica plena y/o suficiente para obligar a dicha entidad por los presentes Términos y Condiciones, utilizar y, en su caso, contratar los Servicios puestos a disposición en el Sitio.</p>
            <p align='justify'>2.3. Los menores de edad que quieran constituirse como Usuarios del Sitio, al momento de su inscripción y/o registración, deberán contar y hacer constar en forma expresa en dicha instancia, con la autorización de su padre, madre, tutor y/o responsable.</p>
            <p align='justify'>2.4. No podrán ser Usuarios y/o utilizar los Servicios del Sitio los menores de edad sin autorización de su madre, padre y/o tutor; quienes no tengan capacidad para contratar; o las personas que hayan sido dadas de baja o suspendidas como Usuarios del Sitio, temporal o definitivamente, por cualquier incumplimiento de los presentes Términos y Condiciones Generales y/o por haber incurrido en conductas o actos dolosos y/o fraudulentos mediante el uso del Sitio y/o los Servicios en él contenidos.</p>
            <h5>3. REGISTRACIÓN / INSCRIPCIÓN.</h5>
            <p align='justify'>3.1. Es obligación de todo futuro Usuario completar el formulario de inscripción en todos sus campos con datos fidedignos y válidos, a los fines de poder utilizar los Servicios ofrecidos por el Sitio. </p>
            <p align='justify'>3.2. El futuro Usuario deberá completar dicho formulario con su información personal de manera exacta, precisa y verdadera (en adelante los “Datos Personales”), y asumirá el compromiso de mantener los Datos Personales actualizados, conforme resulte necesario y/o le sea requerido. </p>
            <p align='justify'>3.3. El Sitio se reserva la posibilidad de utilizar diferentes medios para identificar a los Usuarios, pero no se responsabiliza por la certeza de los Datos Personales provistos por los Usuarios en el formulario de inscripción. </p>
            <p align='justify'>3.4. El Usuario, en todos y cada uno de los casos, garantiza y responde ante la autenticidad, exactitud, veracidad y vigencia de los Datos Personales ingresados en el formulario de inscripción. </p>
            <p align='justify'>3.5. El Sitio se reserva el derecho de solicitar algún comprobante, información y/o dato adicional a efectos de corroborar los Datos Personales, así como de inhabilitar a aquellos Usuarios que en un período razonable no logre contactar o bien, que al momento de la verificación no quieran confirmar sus datos. Procediendo en tal caso, a la inhabilitación del Usuario para utilizar el Sitio y la baja toda la información, intervención y/o actividad registrada por el Usuario en el Sitio, sin que ello genere y/o implique derecho a resarcimiento alguno..</p>
            <p align='justify'>3.6. El Usuario accederá a su Cuenta Personal (en adelante la “Cuenta”) mediante el ingreso de su correo electrónico y/o cuenta a la red social elegida para dicho acceso, y su Password o Clave de Seguridad elegidos por el Usuario al momento de la inscripción. </p>
            <p align='justify'>3.7. La cuenta que el Usuario utilice dentro del Sitio no podrá generar confusiones con el nombre del Sitio. Por lo tanto, no se podrán utilizar cuentas tales como "Sitio1", "HelpoOrg" o similares, de tal forma que los demás Usuarios puedan pensar que la información, actividades y/o interacciones consignadas por estas personas pertenecen al Sitio o hacen parte de promociones llevadas a cabo directamente por el Sitio. El Sitio se reserva el derecho a eliminar del sistema las Cuentas que a criterio del Sitio puedan tener las características a que hace referencia este párrafo. </p>
            <p align='justify'>3.8. El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad y será responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. Asimismo, el Usuario se compromete a notificar al Sitio en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. </p>
            <p align='justify'>3.9. La utilización de la Cuenta es personal y exclusiva de su Usuario titular, por lo que se prohíbe su venta, cesión y/o transferencia bajo ningún título. </p>
            <p align='justify'>3.10. El Sitio se reserva el derecho de rechazar cualquier solicitud de inscripción o de cancelar una inscripción previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere derecho alguno a indemnización o resarcimiento.</p>
            <h5>4. MODIFICACIONES.</h5>
            <p align='justify'>4.1. Helpo se reserva el derecho de modificar, reemplazar, ampliar o restringir; en cualquier momento y sin previo aviso, la configuración del Sitio, la cantidad, contenido y extensión de los Servicios prestados a través del mismo y los presentes Términos y Condiciones Generales.</p>
            <p align='justify'>4.2. Las modificaciones que se efectúen entrarán en vigencia y producirán efecto en forma inmediata a partir de su incorporación y/o publicación en el Sitio.</p>
            <p align='justify'>4.3. Del mismo modo, Helpo se reserva el derecho de restringir, denegar, suspender o interrumpir el acceso al Sitio y/o los Servicios, de forma parcial o total, sin necesidad de preavisar y/o expresar causa alguna.</p>
            <p align='justify'>4.4. Cualquier cambio o restricción sobre el acceso al Sitio y/o los Servicios, entrará en vigor en forma inmediata una vez efectuados.</p>
            <p align='justify'>4.5. Cualquiera sea el caso, en el primer ingreso inmediato posterior que el Usuario efectúe al Sitio, deberá manifestar si acepta las modificaciones efectuadas, caso contrario, el vínculo que por los presentes Términos y Condiciones Generales se establece, quedará disuelto y se procederá en forma inmediata a la inhabilitación de la cuenta registrada por el Usuario en el Sitio.</p>
            <p align='justify'>4.6. Ninguna modificación y/o restricción al acceso, ya sea al Sitio, los Servicios y/o los presentes Términos y Condiciones Generales, generará responsabilidad alguna para Helpo.</p>
            <h5>5. POLÍTICA DE PRIVACIDAD Y PROTECCIÓN DE DATOS.</h5>
            <p align='justify'>5.1. La utilización de los Servicios y/o el acceso al Sitio puede requerir la identificación del Usuario en el Sitio, previa cumplimentación de un formulario de registro y/o inscripción, donde el Usuario deberá ingresar datos, que se limitarán a los que resulten necesarios para la prestación de los Servicios.</p>
            <p align='justify'>5.2. El aporte de los datos será facultativo para el titular de los mismos, salvo aquella información que se requiera en observancia de obligaciones legales y/o regulatorias. </p>
            <p align='justify'>5.3. Los Datos Personales que sean suministrados por el Usuario se almacenarán en servidores o medios magnéticos que cumplen con las exigencias en materia de seguridad y protección, tanto física como tecnológica.</p>
            <p align='justify'>5.4. Los Términos y Condiciones cumplen con los requisitos exigidos por la ley 25.326 sobre Protección de Datos Personales, su reglamentación por Decreto N° 1558/2001 y el Decreto modificatorio N° 1160/2010, encontrándose Helpo comprometida con el resguardo de la intimidad de los Usuarios, a excepción de las acciones de terceros por quienes Helpo no debe responder.</p>
            <p align='justify'>5.5. Sin perjuicio de lo anterior y de que Helpo asegura la confidencialidad de los datos suministrados por los Usuarios, los Datos Personales podrán ser revelados a las Autoridades Públicas competentes que los requieran de conformidad y en cumplimiento con las disposiciones legales y reglamentarias aplicables al caso.</p>
            <p align='justify'>5.6. El Usuario registrado puede ejercer en forma gratuita el derecho de acceso a los Datos Personales ingresados al Sitio Web, pudiendo ejercitar los derechos de acceso, cancelación, rectificación y oposición. </p>
            <p align='justify'>5.7. Toda persona física o jurídica que se registre como Usuario, garantiza la autenticidad, exactitud y vigencia de todos aquellos datos que informe, siendo la única responsable de mantenerlos debidamente actualizados, no asumiendo Helpo ninguna responsabilidad en el caso de inexactitud de los Datos Personales ingresados por el Usuario en el Sitio.</p>
            <p align='justify'>5.8. Helpo no negociará, venderá, cederá, ni alquilará los Datos Personales y/o la información con la que cuente. Dichos datos y/o información serán utilizados en forma exclusiva y excluyente para la búsqueda, selección, interacción y demás acciones necesarias para una correcta utilización del Sitio, con el objeto de oficiar como nexo de relación entre los distintos Usuarios.</p>
            <h5>6. GRATUIDAD.</h5>
            <p align='justify'>El registro como Usuario del Sitio, así como toda utilización e interacción en el Sitio es gratuita, no debiendo el Usuario abonar nada por interactuar y/o concertar acciones de colaboración y/o trabajo conjunto con otros Usuarios por intermedio del Sitio.</p>
            <h5>7. DERECHOS Y OBLIGACIONES DE LOS USUARIOS.</h5>
            <p align='justify'>7.1. Los Términos y Condiciones Generales establecen para los Usuarios los siguientes derechos:</p>
            <p align='justify'>7.1.1. - A no ser discriminados por razón alguna, respetando su personalidad, dignidad humana e intimidad.</p>
            <p align='justify'>7.1.2. - A recibir en todo momento un trato humano, amable, comprensivo y respetuoso.</p>
            <p align='justify'>7.1.3. - A recibir en todo momento la información y, orientación para la correcta utilización del Sitio y sus Servicios.</p>
            <p align='justify'>7.2. Los Términos y Condiciones Generales establecen los siguientes deberes de los Usuarios:</p>
            <p align='justify'>7.2.1. - Mantener actualizados permanentemente sus Datos Personales.</p>
            <p align='justify'>7.2.2. - Cumplir los compromisos adquiridos con las organizaciones en las que se integren, con motivo y/o en virtud de las relaciones que se establezcan por intermedio del Sitio, respetando los fines y la normativa de las mismas.</p>
            <p align='justify'>7.2.3. - Guardar, cuando proceda, confidencialidad de la información recibida y conocida en el desarrollo de su actividad.</p>
            <p align='justify'>7.2.4. - Respetar los derechos de los demás Usuarios del Sitio.</p>
            <p align='justify'>7.2.5. - Actuar siempre y en todo momento con responsabilidad, buena fe, en forma diligente, eficiente, eficaz y solidaria.</p>
            <p align='justify'>7.2.6. - Seguir las instrucciones adecuadas que se impartan en el desarrollo de las actividades encomendadas a los fines de cumplir el objeto de las mismas.</p>
            <h5>8. VIOLACIONES AL SISTEMA, AL SITIO Y/O SUS BASES DE DATOS.</h5>
            <p align='justify'>8.1. No está permitido el uso de ningún dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria del Sitio como en las bases de datos del Sitio o su sistema. </p>
            <p align='justify'>8.2. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de autor y/o a las prohibiciones estipuladas en estos Términos y Condiciones Generales harán pasible a su responsable de las acciones legales que correspondieren y los daños y perjuicios ocasionados.</p>
            <h5>9. INCUMPLIMIENTO A LOS TÉRMINOS Y CONDICIONES GENERALES.</h5>
            <p align='justify'>9.1. Ante el incumplimiento, por parte de un Usuario, de cualquiera de las estipulaciones de los Términos y Condiciones Generales, o de cualquier otro compromiso asumido por el Usuario frente a otros en el ámbito de los Servicios del Sitio y/o ante actos o conductas dolosas o fraudulentas; Helpo podrá, sin perjuicio de otras medidas, advertir, suspender o cancelar, temporal o definitivamente la Cuenta del Usuario, dejar de prestar los Servicios y en su caso, iniciar las acciones legales que pudieren corresponder.</p>
            <p align='justify'>9.2. En el caso de la suspensión o inhabilitación de un Usuario, sus Datos Personales y toda la información y actividad registrada y publicada, vinculada a dicho Usuario, será removida del sistema y del Sitio, salvo que la misma sea requerida por las Autoridades Administrativas competentes y/o sirviese como prueba de eventuales investigaciones de actos delictivos.</p>
            <p align='justify'>9.3. Helpo se reserva el derecho de cancelar la Cuenta del Usuario que hubiere incumplido sus obligaciones, o si se detectara en su conducta intencionalidad de perjudicar a otros Usuarios. </p>
            <p align='justify'>9.4. Sin perjuicio de las razones mencionadas, Helpo se reserva el derecho a cancelar una Cuenta si considera que el Usuario ha incurrido en algún error involuntario y/o por cualquier otra razón que Helpo considere justificada. </p>
            <p align='justify'>9.5. Si el Usuario no estuviere de acuerdo con el contenido de estos Términos y Condiciones Generales, deberá abstenerse de acceder y operar a través del Sitio.</p>
            <h5>10. EXCLUSIÓN DE GARANTÍAS Y RESPONSABILIDAD.</h5>
            <p align='justify'>10.1. Atento a que el Sitio pone a disposición Servicios que constituyen un beneficio opcional y gratuito para los Usuarios, Helpo no responde por los daños y/o perjuicios que el uso del Sitio y/o los Servicios pudiesen generar.</p>
            <p align='justify'>10.2. El Sitio permite a los Usuarios ponerse en comunicación y/o interactuar entre sí, en forma libre y voluntaria, a través del medio que consideren y elijan como el más adecuado.</p>
            <p align='justify'>10.3. En tal sentido, Helpo no es propietario, patrocinador y/o responsable de los datos suministrados por los Usuarios y consignados en el Sitio.</p>
            <p align='justify'>10.4. Helpo no interviene en el perfeccionamiento de las interacciones y/o vínculos que se generen entre los Usuarios, ni las condiciones en las que se realizan las mismas. En consecuencia, Helpo no responde por la existencia, contenido, estado, integridad y/o legitimidad de dichas relaciones, así como la capacidad para contratar de los Usuarios o la veracidad de los Datos Personales por ellos ingresados.</p>
            <p align='justify'>10.5. Cada Usuario conoce y acepta ser el exclusivo responsable por los Datos Personales y demás información que publica, y por las actividades que realiza en el Sitio. </p>
            <p align='justify'>10.6. Debido a que Helpo no tiene ninguna participación ni injerencia durante todo el tiempo en que los Usuarios se dan a conocer y/o interactúan, no será responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de las interacciones y/o acciones de colaboración que acuerden. </p>
            <p align='justify'>10.7. El Usuario conoce y acepta que al interactuar con otros Usuarios o terceros lo hace bajo su propio riesgo. </p>
            <p align='justify'>10.8. En ningún caso Helpo será responsable por ningún daño, perjuicio y/o lucro cesante que haya podido sufrir el Usuario, debido a las interacciones, acciones de colaboración y/o cualquier otra. </p>
            <p align='justify'>10.9. Helpo recomienda actuar con la debida prudencia y debida diligencia, al momento de realizar interacciones con otros Usuarios. El Usuario debe tener presentes, además, los riesgos de contactar con menores de edad o con personas que se valgan de una identidad falsa. </p>
            <p align='justify'>10.10. Dado el enorme volumen de la comunidad electrónica, Helpo no puede constatar la veracidad y exactitud de los datos consignados por los Usuarios al registrarse en el Sitio. En tal sentido, Helpo no será responsable por las publicaciones o las interacciones realizadas con otros Usuarios basadas en la confianza depositada en el Sitio o los Servicios brindados. </p>
            <p align='justify'>10.11. En caso que uno o más Usuarios o algún tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a Helpo, sus directores, gerentes, empleados, agentes, operarios, representantes y apoderados.</p>
            <h5>11. ALCANCE DEL SERVICIO.</h5>
            <p align='justify'>11.1. Los Términos y Condiciones Generales no crean ningún contrato de sociedad, mandato, franquicia, publicidad, o relación laboral entre el Sitio y el Usuario.</p>
            <p align='justify'>11.2. El Usuario reconoce y acepta que el Sitio no es parte en ninguna operación, ni tiene control alguno sobre la calidad, cantidad, estado, integridad, seguridad, legitimidad o legalidad de los datos, información, y publicaciones anunciadas, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para operar, obrar y/o interactuar, así como la capacidad para contratar de los Usuarios.</p> 
            <p align='justify'>11.3. Los Usuarios reconocen que toda interacción, relación y eventuales acciones conjuntas entre ellos, está sujeta a regulaciones específicas que se obligan a cumplimentar. </p>
            <h5>12. FALLAS EN SITIO Y SU SISTEMA.</h5> 
            <p align='justify'>12.1. Helpo no se responsabiliza por cualquier daño, perjuicio o pérdida en el equipo del Usuario causada por fallos en el sistema, en el servidor o en Internet. Tampoco será responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o examen de su Sitio o a raíz de cualquier transferencia de datos, archivos, imágenes, textos o audio contenidos en el mismo. </p>
            <p align='justify'>12.2. Los Usuarios NO podrán imputarle responsabilidad alguna ni exigir pago por daño emergente o lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas o fallos en los sistemas o en Internet.</p>
            <p align='justify'>12.3. Helpo no garantiza el acceso y uso continuado o ininterrumpido de su Sitio, que puede eventualmente no estar disponible por dificultades técnicas o fallos de Internet, o por cualquier otra circunstancia ajena a el Sitio; en tales casos se procurará restablecerlo con la mayor rapidez posible sin que por ello pueda imputársele algún tipo de responsabilidad. </p>
            <p align='justify'>12.4. Helpo tampoco será responsable por ningún error u omisión contenidos en su sitio web.</p>
            <h5>13. INTEGRIDAD DE LOS TÉRMINOS Y CONDICIONES.</h5>
            <p align='justify'>La eventual invalidez o nulidad de alguna o algunas de las cláusulas de los Términos y Condiciones Generales no implican la invalidez de las restantes cláusulas ni de los principios de buena fe contractual que, tanto Helpo como el Usuario, verosímilmente entendieron o debieron entender actuando con cuidado y previsión.</p>
            <h5>14. PROPIEDAD INTELECTUAL.</h5>
            <p align='justify'>Los contenidos de las pantallas relativas a los Servicios del Sitio como así también los programas, bases de datos, redes, archivos que permiten al Usuario acceder y usar su Cuenta, son de propiedad de Helpo y están protegidas por las leyes y tratados internacionales de derecho de autor, marcas, patentes, modelos y diseños industriales. El uso indebido y la reproducción total o parcial de dichos contenidos, salvo autorización expresa y por escrito de Helpo, quedan prohibidos, están penados por la ley con sanciones civiles y/o penales, y serán objeto de todas las acciones judiciales pertinentes.  El Sitio respeta la propiedad intelectual y solicita a sus Usuarios idéntica obligación. </p>
            <h5>15. INDEMNIDAD.</h5>
            <p align='justify'>El Usuario mantendrá indemne a Helpo, sus filiales, empresas controladas y/o controlantes, directivos, administradores, representantes y empleados, por cualquier reclamo o demanda de otros Usuarios o terceros por sus actividades en el Sitio y/o por su incumplimiento de los Términos y Condiciones Generales, y/o por la violación de cualesquier ley o derechos de terceros, incluyendo los honorarios de abogados.</p>
            <h5>16. DATOS DE CONTACTO.</h5> 
            <p align='justify'>Los datos que identifican a Helpo, responsable del Sitio, y a los cuales el Usuario podrá dirigirse para ejercer sus derechos, son los detallados a continuación: E-mail [consultas@helpo.com.ar].</p> 
            <h5>17. LEY APLICABLE, INTERPRETACIÓN Y JURISDICCIÓN.</h5>  
            <p align='justify'>17.1. Los presentes Términos y Condiciones se interpretarán y regirán de conformidad con las leyes vigentes en la República Argentina.</p>
            <p align='justify'>17.2. Asimismo, los Términos y Condiciones Generales deben interpretarse considerando la voluntad libre y conscientemente expresada, de utilizar el Sitio y/o los Servicios a los cuales se accede por el mismo.</p>
            <p align='justify'>17.3. Ante la posibilidad de que existan disposiciones adicionales y/o específicas establecidas para el uso puntual de alguno de los Servicios, dichas disposiciones deberán ser interpretadas en conjunto y concordancia con las contenidas en los presente Términos y Condiciones Generales.</p>
            <p align='justify'>17.4. En caso de conflicto entre las disposiciones contenidas en los presentes Términos y Condiciones Generales y las disposiciones adicionales o específicas, estas últimas prevalecerán sobre las generales.</p>
            <p align='justify'>17.5. Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretación, alcance o cumplimiento, será sometida a los Tribunales con Competencia Ordinaria de la Provincia de Córdoba. Las partes renuncian al fuero Federal y/o todo otro de excepción que les pudieren corresponder.</p>
          </CardBody>
        </Card>
      </div>
    );
  }
}

export default PageTyC;