from users.infrastructure.repositories.users import DjangoORMUsersRepository
from users.infrastructure.repositories.volunteer_profiles import DjangoORMVolunteerProfilesRepository
from users.infrastructure.repositories.skills import DjangoORMSkillsRepository
from users.infrastructure.repositories.organization_areas import DjangoORMOrganizationAreasRepository
