export const LOAD_EVENTOS_SUCCESS = 'LOAD_EVENTOS_SUCCESS';
export const LOAD_EVENTOS_PROXIMOS_SUCCESS = 'LOAD_EVENTOS_PROXIMOS_SUCCESS';
export const LOAD_RUBROS_EVENTO_SUCCESS = 'LOAD_RUBROS_EVENTO_SUCCESS';
export const LOAD_EVENTOS_ORGANIZACION_SUCCESS = 'LOAD_EVENTOS_ORGANIZACION_SUCCESS';
export const LOAD_EVENTOS_CON_COLABORACIONES_SUCCESS = 'LOAD_EVENTOS_CON_COLABORACIONES_SUCCESS'
export const UPDATE_EVENTOS_SUCCESS = 'UPDATE_EVENTOS_SUCCESS';
export const DELETE_EVENTOS_SUCCESS = 'UPDATE_EVENTOS_SUCCESS';
// Mis Colaboraciones
export const LOAD_MIS_COLABORACIONES_SUCCESS = 'LOAD_MIS_COLABORACIONES_SUCCESS'
export const MIS_COLABORACIONES_HAS_LOADED = 'MIS_COLABORACIONES_HAS_LOADED'
export const MIS_COLABORACIONES_HAS_ERROR = 'MIS_COLABORACIONES_HAS_ERROR'