export const LOAD_EVENTOS_SUCCESS = 'LOAD_EVENTOS_SUCCESS';
export const LOAD_EVENTOS_PROXIMOS_SUCCESS = 'LOAD_EVENTOS_PROXIMOS_SUCCESS';
export const LOAD_RUBROS_EVENTO_SUCCESS = 'LOAD_RUBROS_EVENTO_SUCCESS';
export const LOAD_EVENTOS_ORGANIZACION_SUCCESS = 'LOAD_EVENTOS_ORGANIZACION_SUCCESS';
export const LOAD_EVENTOS_CON_COLABORACIONES_SUCCESS = 'LOAD_EVENTOS_CON_COLABORACIONES_SUCCESS'
export const UPDATE_EVENTOS_SUCCESS = 'UPDATE_EVENTOS_SUCCESS';
export const DELETE_EVENTOS_SUCCESS = 'UPDATE_EVENTOS_SUCCESS';
// Mis Colaboraciones
export const LOAD_CONSULTAR_COLABORACIONES_SUCCESS = 'LOAD_CONSULTAR_COLABORACIONES_SUCCESS'
export const CONSULTAR_COLABORACIONES_HAS_LOADED = 'CONSULTAR_COLABORACIONES_HAS_LOADED'
export const CONSULTAR_COLABORACIONES_HAS_ERROR = 'CONSULTAR_COLABORACIONES_HAS_ERROR'
export const CHANGE_COLABORACION_ENTREGA = 'CHANGE_COLABORACION_ENTREGA'
export const CHANGE_COLABORACION_PARTICIPACION = 'CHANGE_COLABORACION_PARTICIPACION'
export const SEND_CONSULTAR_COLABORACIONES_DATA = 'SEND_CONSULTAR_COLABORACIONES_DATA'
export const SEND_CONSULTAR_COLABORACIONES_SUCCESFUL = 'SEND_CONSULTAR_COLABORACIONES_SUCCESFUL'
export const SEND_CONSULTAR_COLABORACIONES_HAD_ERROR = 'SEND_CONSULTAR_COLABORACIONES_HAD_ERROR'
//Album Evento
export const GET_ALBUM_EVENTO_PROPS = 'GET_ALBUM_EVENTO_PROPS'
export const FETCH_ALBUM_EVENTO_IMAGENES_SUCCESS = 'FETCH_ALBUM_EVENTO_IMAGENES_SUCCESS'
export const FETCH_ALBUM_EVENTO_IMAGENES_FAILURE = 'FETCH_ALBUM_EVENTO_IMAGENES_FAILURE'
export const FETCH_ALBUM_EVENTO_IMAGENES_LOADING = 'FETCH_ALBUM_EVENTO_IMAGENES_LOADING'

