export const LOAD_EVENTOS_SUCCESS = 'LOAD_EVENTOS_SUCCESS';
export const LOAD_EVENTOS_PROXIMOS_SUCCESS = 'LOAD_EVENTOS_PROXIMOS_SUCCESS';
export const LOAD_RUBROS_EVENTO_SUCCESS = 'LOAD_RUBROS_EVENTO_SUCCESS';
export const LOAD_EVENTOS_ORGANIZACION_SUCCESS = 'LOAD_EVENTOS_ORGANIZACION_SUCCESS';
export const UPDATE_EVENTOS_SUCCESS = 'UPDATE_EVENTOS_SUCCESS';
