# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_auto_20180511_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=140, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.CategoriaRecurso')),
            ],
        ),
        migrations.AddField(
            model_name='necesidad',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.Recurso'),
        ),
    ]
