# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20180522_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='necesidad',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
