# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_auto_20180524_2021'),
        ('actividades', '0005_contacto'),
    ]

    operations = [
    ]
