# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_auto_20180602_1748'),
        ('actividades', '0010_auto_20180705_1911'),
    ]

    operations = [
    ]
