# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_auto_20180705_1911'),
        ('actividades', '0010_auto_20180622_0332'),
    ]

    operations = [
    ]
