# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_merge_20180709_2158'),
        ('actividades', '0011_merge_20180708_2248'),
    ]

    operations = [
    ]
