# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_merge_20180710_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=140, null=True)),
                ('cantidad', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='actividades.Evento')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.Funcion')),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necesidades', to='actividades.Evento'),
        ),
    ]
