# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_colaboracion_participacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacion',
            name='cantidad',
        ),
    ]
