# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0016_auto_20180724_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboracion',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participacion',
            name='participo',
            field=models.BooleanField(default=False),
        ),
    ]
