# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0018_merge_20180828_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboracion',
            old_name='retroalimentacion',
            new_name='retroalimentacion_voluntario',
        ),
        migrations.RenameField(
            model_name='participacion',
            old_name='retroalimentacion',
            new_name='retroalimentacion_voluntario',
        ),
        migrations.AddField(
            model_name='colaboracion',
            name='retroalimentacion_ong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participacion',
            name='retroalimentacion_ong',
            field=models.BooleanField(default=False),
        ),
    ]
