# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0019_auto_20180830_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=140)),
                ('execute_date', models.DateTimeField()),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.Evento')),
            ],
        ),
    ]
