# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-02 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0021_auto_20180902_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmensaje',
            old_name='evento',
            new_name='mensaje',
        ),
    ]
