# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-02 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0022_auto_20180902_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='Sin asunto', max_length=100),
            preserve_default=False,
        ),
    ]
