# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-02 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0022_eventoimagen'),
        ('actividades', '0022_auto_20180902_1722'),
    ]

    operations = [
    ]
