# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0023_mensaje_asunto'),
        ('actividades', '0023_merge_20180902_2257'),
    ]

    operations = [
    ]
