# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-08 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0025_auto_20180907_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboracion',
            old_name='voluntario',
            new_name='colaborador',
        ),
        migrations.RenameField(
            model_name='participacion',
            old_name='voluntario',
            new_name='colaborador',
        ),
    ]
