# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-08 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0026_auto_20180908_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
