# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-08 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0027_participacion_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ofrecimiento',
            new_name='Pedido',
        ),
    ]
