# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0028_auto_20180908_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmensaje',
            old_name='voluntario',
            new_name='usuario',
        ),
    ]
