# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-14 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0030_auto_20180909_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='actividades.Evento'),
        ),
    ]
