# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0032_auto_20180916_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboracion',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboracion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
