# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0032_auto_20180916_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='colaboracion',
            name='entregado',
        ),
        migrations.AddField(
            model_name='evento',
            name='campaña',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrega',
            name='colaboracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='actividades.Colaboracion'),
        ),
    ]
