# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-06 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0033_auto_20180928_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to=settings.AUTH_USER_MODEL),
        ),
    ]
