# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0033_auto_20180928_2124'),
        ('actividades', '0033_auto_20180926_0252'),
    ]

    operations = [
    ]
