# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0034_merge_20181004_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.IntegerField()),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='actividades.Participacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='colaboracion',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to=settings.AUTH_USER_MODEL),
        ),
    ]
