# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-10 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0034_auto_20181006_0141'),
        ('actividades', '0035_auto_20181004_2354'),
    ]

    operations = [
    ]
