# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-11 23:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0036_merge_20181010_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horarios',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=None), default=[], size=None),
        ),
    ]
