# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180526_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
