# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rubroorganizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isExternal', models.BooleanField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('notas', models.CharField(max_length=140, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='organizacionprofile',
            name='cuit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacionprofile',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacionprofile',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.RubroOrganizacion'),
        ),
        migrations.AddField(
            model_name='organizacionprofile',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacionprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Imagen'),
        ),
        migrations.AddField(
            model_name='organizacionprofile',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Ubicacion'),
        ),
    ]
