# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180708_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Imagen'),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='cuit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.RubroOrganizacion'),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Ubicacion'),
        ),
        migrations.AddField(
            model_name='voluntarioprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Imagen'),
        ),
        migrations.AddField(
            model_name='voluntarioprofile',
            name='dni',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntarioprofile',
            name='gustos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntarioprofile',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntarioprofile',
            name='sexo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntarioprofile',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voluntarioprofile',
            name='apellido',
            field=models.CharField(default='no apellido', max_length=140),
        ),
    ]
