# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180709_1751'),
        ('users', '0005_auto_20180609_1843'),
    ]

    operations = [
    ]
