# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaprofile',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
