# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180822_0226'),
        ('users', '0009_auto_20180818_1443'),
    ]

    operations = [
    ]
