# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-19 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180915_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='empresaprofile',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.RubroEmpresa'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscriptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL),
        ),
    ]
