# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-23 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180919_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWrapper',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_token', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
