# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180919_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizacionSuscripcionesMensuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('suscripciones', models.IntegerField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
