# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_smsverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprofile',
            name='verificada',
            field=models.BooleanField(default=False),
        ),
    ]
