# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-29 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_empresaprofile_verificada'),
        ('users', '0014_organizacionsuscripcionesmensuales'),
    ]

    operations = [
    ]
