# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-06 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20180929_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacionsuscripcionesmensuales',
            options={'ordering': ['-fecha']},
        ),
    ]
