# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-02 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_merge_20181010_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.BigIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=70, null=True)),
                ('last_name', models.CharField(default='no last name', max_length=140)),
                ('birth_date', models.DateField()),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('work_position', models.CharField(max_length=140, null=True)),
                ('profession', models.CharField(max_length=140, null=True)),
                ('educational_level', models.CharField(max_length=140, null=True)),
                ('availability', models.CharField(max_length=280, null=True)),
                ('modality', models.CharField(max_length=70, null=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Imagen')),
                ('interests', models.ManyToManyField(to='users.RubroOrganizacion')),
                ('skills', models.ManyToManyField(to='users.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='voluntarioprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='voluntarioprofile',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='VoluntarioProfile',
        ),
    ]
