# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-03 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200502_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RubroOrganizacion',
            new_name='OrganizationArea',
        ),
    ]
