# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-03 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200503_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerprofile',
            old_name='genre',
            new_name='gender',
        ),
    ]
