# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200503_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.State'),
        ),
    ]
