# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-24 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_volunteerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='dni',
        ),
    ]
