# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_volunteerprofile_work_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='modality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Modality'),
        ),
    ]
