# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200525_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='experience',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
