# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_volunteerprofile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacionprofile',
            name='rubro',
        ),
        migrations.AddField(
            model_name='organizacionprofile',
            name='rubros',
            field=models.ManyToManyField(to='users.OrganizationArea'),
        ),
    ]
