# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd helpo-api && pip install -r requirements.txt
    - name: Test
      run: |
        cd helpo-api && python -m coverage run manage.py test
        cd helpo-api && ./wait-for-it.sh localhost:5432 -- bash -c
        cd helpo-api && DJANGO_SETTINGS_MODULE=helpo.settings.test && python manage.py migrate
        cd helpo-api && DJANGO_SETTINGS_MODULE=helpo.settings.test && SECRET_KEY=$(python -c 'import uuid; print(uuid.uuid4().hex + uuid.uuid4().hex)') && python manage.py populate_db
        cd helpo-api && DJANGO_SETTINGS_MODULE=helpo.settings.production && SECRET_KEY=$(python -c 'import uuid; print(uuid.uuid4().hex + uuid.uuid4().hex)') && DATABASE_URL='sqlite:///' && ALLOWED_HOSTS='.example.org' && SENDGRID_USERNAME='test' && SENDGRID_PASSWORD='test' && REDIS_URL='redis://' python manage.py check --deploy
        cd helpo-api && python -m coverage run manage.py test
        
