name: helpo-messenger units
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'
      - run: cd helpo-messenger && mix deps.get
      - run: cd helpo-messenger && mix test --cover
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
          file: ./helpo-messenger/cover/coverage.xml
